2020-04-24 12:50:27,047 ERROR: Exception on /Myna/Post [POST] [in /home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/Myna/routes.py", line 38, in post
    post = Post(body=form.post.data, author=current_user.username)
  File "<string>", line 4, in __init__
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 842, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 272, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1018, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1041, in fire_replace_event
    state, value, previous, initiator or self._replace_token
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1450, in emit_backref_from_scalar_set_event
    instance_state(child),
AttributeError: 'str' object has no attribute '_sa_instance_state'
2020-04-24 12:50:38,337 ERROR: Exception on /Myna/Post [POST] [in /home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/Myna/routes.py", line 38, in post
    post = Post(body=form.post.data, author=current_user.username)
  File "<string>", line 4, in __init__
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 842, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 272, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1018, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1041, in fire_replace_event
    state, value, previous, initiator or self._replace_token
  File "/home/sartho/Coding/Project/GreenAnt/sys/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1450, in emit_backref_from_scalar_set_event
    instance_state(child),
AttributeError: 'str' object has no attribute '_sa_instance_state'
2020-05-05 16:48:56,410 INFO: Myna startup [in D:\GreenAnt\Myna\__init__.py:62]
